# Generated by Django 2.2.17 on 2021-04-04 10:18

from django.db import migrations, models
import django.db.models.deletion
import fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', fields.ApproximateDateField(blank=True)),
                ('end_date', fields.ApproximateDateField(blank=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_names', to='places.Place')),
            ],
        ),
    ]
