# Generated by Django 2.2.17 on 2021-04-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['-end_date', '-start_date', 'name']},
        ),
    ]
