# Generated by Django 2.2.17 on 2021-04-05 19:42

from django.db import migrations, models
import django.db.models.deletion
import fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('places', '0003_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['-end_date', '-start_date', 'name']},
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('town', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, choices=[('proscenium', 'Proscenium Arch'), ('thrust', 'Thrust'), ('multiple', 'Multiple'), ('other', 'Other')], max_length=100)),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Seats')),
                ('opening_date', fields.ApproximateDateField(blank=True)),
                ('closing_date', fields.ApproximateDateField(blank=True, default='')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.Country')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='places.Place')),
            ],
            options={
                'ordering': ['-opening_date'],
            },
        ),
    ]
