# Generated by Django 2.2.17 on 2021-04-05 19:42

from django.db import migrations


FIELDS = ('latitude', 'longitude', 'address', 'town', 'country', 'postcode', 'telephone', 'type', 'size', 'opening_date', 'closing_date')


def move_locations(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    Location = apps.get_model('places', 'Location')
    for place in Place.objects.all():
        any_set = [field for field in FIELDS if getattr(place, field)]
        if not any_set:
            continue
        loc = Location()
        loc.place = place
        for field in FIELDS:
            setattr(loc, field, getattr(place, field))
        loc.save()


def move_locations_back(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    Location = apps.get_model('places', 'Location')
    for loc in Location.objects.all():
        place = loc.place
        for field in FIELDS:
            setattr(place, field, getattr(loc, field))
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210405_1942'),
    ]

    operations = [
        migrations.RunPython(move_locations, move_locations_back),
    ]
