# Generated by Django 2.2.17 on 2021-04-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20210405_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='opening_date',
        ),
        migrations.RemoveField(
            model_name='place',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='place',
            name='size',
        ),
        migrations.RemoveField(
            model_name='place',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='place',
            name='town',
        ),
        migrations.RemoveField(
            model_name='place',
            name='type',
        ),
    ]
