plays = [
 {'cast': [u'Toyah Wilcox',
           u'Damian Williams',
           u'Toby Foster',
           u'Andrew Alexander',
           u'Kate Quinnell',
           u'Bobby Knutt'],
  'dates': set([(('2009-12-11', '2010-01-10'), u'Lyceum Theatre, Sheffield')]),
  'description': u'written and directed by Paul Hendy musical direction by Andy Booth choreographed by Rachel Lane',
  'links': {u'http://www.evolution-productions.co.uk': ''},
  'pictures': set([u'http://www.its-behind-you.com/images/09Sheffield.jpg']),
  'producer': '',
  'producerImg': u'http://www.its-behind-you.com/images/evolutionslogo.jpg',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': 'Snow White',
  'titleImg': u'http://www.its-behind-you.com/images/EvoSnowWhite-3.jpg',
},
 {'cast': [u'Kay Purcell',
           u'Francis and Wheatley',
           u'Chris Casserly',
           u'Ian Billings',
           u'Victoria Scott',
           u'Ashleigh Jones'],
  'dates': set([(('2009-12-10', '2010-01-03'), u'The Place Theatre , Telford')]),
  'description': u'written by Keith Simmons with additional material by Ian Billings directed by Ian Billings choreographed by Drew Varley',
  'links': {u'http://www.paulholmanassociates.co.uk': ''},
  'pictures': set([u'http://www.its-behind-you.com/images/09Telford.jpg']),
  'producer': '',
  'producerImg': u'http://www.its-behind-you.com/images/holmanlogo.jpg',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': 'Snow White',
  'titleImg': u'http://www.its-behind-you.com/images/HolmanSWLogo-2.jpg',
},
 {'cast': [],
  'dates': set([(('', ''), u'Campus West Theatre, Welwyn Garden City')]),
  'description': '',
  'dupe': 185,
  'links': {u'http://www.campuswest.co.uk/theatre/': u'Welwyn Garden City',
            u'http://www.welhat.gov.uk/leisureculture/campuswest/campuswestartsconferencecentre': u'Campus West Theatre,'},
  'pictures': set([]),
  'producer': '',
  'producerImg': u'http://www.its-behind-you.com/images/madaboutproductionslogo.jpg',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': u'Snow White',
  'titleImg': '',
},
 {'cast': [u'Vicki Michelle',
           u'Peter Duncan',
           u'Nick Wilton',
           u'Jody Crosier',
           u'Felicity Wright',
           u'Kevin Bohan',
           u'Sarah Luscombe',
           u'Nathan Goy',
           u'Holly Holt',
           u'Andrew Kinning',
           u'Helen Morrish',
           u'Meghan Jane Reid',
           u'Abby Taylor'],
  'dates': set([(('2009-12-14', '2010-01-10'), u'Playhouse, Weston-Super-Mare')]),
  'description': u'written by Keith Simmons directed and choreographed by David Samuel musical direction by Colin Billing',
  'links': {u'http://www.paulholmanassociates.co.uk': ''},
  'pictures': set([u'http://www.its-behind-you.com/images/09Weston.jpg']),
  'producer': '',
  'producerImg': u'http://www.its-behind-you.com/images/holmanlogo.jpg',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': 'Snow White',
  'titleImg': u'http://www.its-behind-you.com/images/HolmanSWLogo-2.jpg',
},
 {'cast': [u'Aaron Sidwell', u"Wayne 'Doom' Gordon", u'Holly Matthews'],
  'dates': set([(('2009-12-05', '2010-01-10'), u'Hazlitt Theatre, Maidstone')]),
  'description': '',
  'dupe': 187,
  'links': {u'http://www.newworldinfo.co.uk': u'New World Productions'},
  'pictures': set([u'http://www.its-behind-you.com/images/09Maidstone.jpg']),
  'producer': u'New World Productions',
  'producerImg': u'http://www.its-behind-you.com/images/newworldproductions_small.jpg',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': u'Snow White',
  'titleImg': '',
},
 {'cast': [u'Sue Holderness',
           u'Laura Sicurello',
           u'Edward Duly-Baker',
           u'Ian Marr'],
  'dates': set([(('2009-12-10', '2010-01-09'), u'Ferneham Hall, Fareham')]),
  'description': '',
  'links': {},
  'pictures': set([]),
  'producer': u'Chris Jordan Productions',
  'producerImg': '',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': 'Snow White',
  'titleImg': u'http://www.its-behind-you.com/images/09Fernehamlogo.jpg',
},
 {'cast': [u'Nigel Ellacott',
           u'Isobel Hurll',
           u'Loraine Porter',
           u'Robert Quarry',
           u'Michael Conway',
           u'Ellie Robertson',
           u'Jocelyn Prah',
           u'Rikki Stone',
           u'Owen Smith',
           u'Tami Stone'],
  'dates': set([(('2009-12-17', '2010-01-23'), u'Kenneth More Theatre, Ilford')]),
  'description': u'written by Nigel Ellacott directed by Vivyan Ellacott musical direction by Stuart Rush choreographed by Loraine Porter',
  'links': {u'http://www.its-behind-you.com/damesdiary20092010.html': ''},
  'pictures': set([u'http://www.its-behind-you.com/images/09Ilford.jpg']),
  'producer': u'Redbridge Theatre Company Limited',
  'producerImg': '',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': u'Snow White',
  'titleImg': '',
},
 {'cast': [],
  'dates': set([(('2009-12-11', '2010-01-03'), u'Princes Hall, Aldershot')]),
  'description': '',
  'dupe': 190,
  'links': {},
  'pictures': set([]),
  'producer': u'Robert Hopkins Associates',
  'producerImg': '',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': u'Snow White',
  'titleImg': '',
},
 {'cast': [u'Lynne McGranger'],
  'dates': set([(('2009-12-11', '2010-01-03'), u'Grand Opera House, York')]),
  'description': '',
  'links': {},
  'pictures': set([]),
  'producer': u'New Pantomime Productions',
  'producerImg': u'http://www.its-behind-you.com/images/newpantologo-small.jpg',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': 'Snow White and the Seven Dwarfs',
  'titleImg': u'http://www.its-behind-you.com/images/nppswweb.jpg',
},
 {'cast': [u'Michael Anderson',
           u'Gavin Ashbarry',
           u'Barry Clark',
           u'Rob Copeland',
           u'Damian Hunt',
           u'Julie Matherson',
           u'Lucy Williamson'],
  'dates': set([(('2009-12-12', '2010-01-03'), u'Radlett Centre, Radlett')]),
  'description': u'written by Shirley Bull directed and choreographed by Victoria Ward musical direction by Alexander Bermange',
  'links': {},
  'pictures': set([]),
  'producer': u'Upstage Productions',
  'producerImg': '',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': u'Snow White and the Seven Dwarfs',
  'titleImg': '',
},
 {'cast': [u'Sarah-Jane Honeywell',
           u'Buster',
           u'Michael Crawshaw',
           u'Phil Lawton'],
  'dates': set([(('2009-12-12', '2010-01-03'), u'Albans Arena,St. Albans')]),
  'description': u'directed and choreographed by Hayley Newnes',
  'links': {},
  'pictures': set([u'http://www.its-behind-you.com/images/09StAlbansCh_small.jpg']),
  'producer': '',
  'producerImg': '',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': 'The Little Mermaid and the Pirates',
  'titleImg': u'http://www.its-behind-you.com/images/littlemermaidNEW_temp.jpg',
},
 {'cast': [u'Dean Park',
           u'Stephen Purdon',
           u'Cat Harvey',
           u'Joyce Falconer',
           u'Des McLean',
           u'Derek Lord',
           u'Douglas Sannachan',
           u'Chris De Rosa'],
  'dates': set([(('2009-12-02', '2010-01-30'), u'Glasgow Pavilion')]),
  'description': '',
  'dupe': 194,
  'links': {},
  'pictures': set([]),
  'producer': '',
  'producerImg': '',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': u'The New Magical Adventures of Pinocchio',
  'titleImg': '',
},
 {'cast': [u'David Spinx',
           u'Laura Hamilton',
           u'Daniel Stockton',
           u'Alistair Divall',
           u'Dominic Cazenove',
           u'Gabrielle Bradshaw',
           u'Kate Richards',
           u'The Character of Mr Bean'],
  'dates': set([(('2009-12-18', '2010-01-03'), u'Woodville Hall Theatre, Gravesend')]),
  'description': '',
  'dupe': 196,
  'links': {},
  'pictures': set([]),
  'producer': '',
  'producerImg': u'http://www.its-behind-you.com/images/Spillers_small.jpg',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': u'The Wizard of Oz',
  'titleImg': '',
},
 {'cast': [u'Chelsie Padley',
           u'Joel Beckett',
           u'Andy Pelos',
           u'Sarah Aveling',
           u'Maurice Byrne',
           u'Jamie Bannerman',
           u'Michelle Whitney'],
  'dates': set([(('2009-12-17', '2010-01-03'), u'Pavilion Theatre, Weymouth')]),
  'description': '',
  'dupe': 197,
  'links': {},
  'pictures': set([]),
  'producer': '',
  'producerImg': u'http://www.its-behind-you.com/images/Spillers_small.jpg',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': u'The Wizard of Oz',
  'titleImg': '',
},
 {'cast': [u'Serena Giacomini',
           u'Kali Hughes',
           u'Clive Flint',
           u'Jack Corcoran',
           u'Julian Eardley',
           u'Jack Cassidy',
           u'Felicity McCormack'],
  'dates': set([(('2009-12-09', '2010-01-03'), u'Theatre Royal, Winchester')]),
  'description': u'written and directed by James Barry music by Simon Slater choreographed by Sally Stanyard',
  'links': {},
  'pictures': set([]),
  'producer': '',
  'producerImg': '',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': u'Wizard of Oz - The Panto',
  'titleImg': '',
},
 {'cast': [],
  'dates': set([(('2009-11-28', '2010-01-03'), u'Tron Theatre, Glasgow')]),
  'description': u'written by Gordon Dougall and Fletcher Mathers',
  'dupe': 198,
  'links': {},
  'pictures': set([]),
  'producer': '',
  'producerImg': '',
  'source': 'http://www.its-behind-you.com/diary20092010.html',
  'title': u'Ya Beauty & The Beast',
  'titleImg': '',
}
]

castLinks = {
 u'Alistair Divall': u'http://www.alistairdivall.co.uk',
 u'Allan Stewart': u'http://www.allanstewart.com/',
 u'Andy Eastwood': u'http://www.andyeastwood.com/Bring-Me-Sunshine.htm',
 u'Andy Ford': u'http://www.andyford.biz',
 u'Antony Costa': u'http://www.antonycosta.biz/',
 u'Antony Stuart-Hicks': u'http://www.antonystuart-hicks.com',
 u'Basil Brush': u'http://www.basilbrush.com',
 u'Ben James-Ellis': u'http://www.benjames-ellis.moonfruit.com/',
 u'Ben Nickless': u'http://www.its-behind-you.com/Ben%20Nickless',
 u'Ben Stock': u'http://www.benstock.biz',
 u'Bernie Clifton': u'http://www.bernieclifton.co.uk',
 u'Bernie Nolan': u'http://www.bernienolan.com/',
 u'Billy Pearce': u'http://www.billypearce.com/',
 u'Brad Fitt': u'http://www.bradfitt.com',
 u'Brenda Cochrane': u'http://www.brendacochrane.com/',
 u'Brian Conley': u'http://www.brianconley.com/',
 u'Cannon and Ball': u'http://www.cannonandball.moonfruit.com/',
 u'Casey-Lee Jolleys': u'http://www.caseyleejolleysacademy.com/',
 u'Ceri Dupree': u'http://www.ceridupree.com',
 u'Chelsie Padley': u'http://www.chelsiepadley.com',
 u'Chesney Hawkes': u'http://www.chesneyhawkes.co.uk',
 u'Chico': u'http://www.1chico.co.uk/index.php',
 u'Chris Clarkson': u'http://www.chris-clarkson.com',
 u'Chris Fountain': u'http://www.chrisfountain.co.uk/',
 u'Chris Harris': u'http://www.chrisharrisproductions.co.uk',
 u'Chris Till': u'http://www.christill.co.uk',
 u'Christina Baily': u'http://www.christinabaily.com',
 u'Claire Sweeney': u'http://www.clairesweeney.co.uk/',
 u'Colin Baker': u'http://www.freewebs.com/colinbaker/',
 u'Craig Revel Horwood': u'http://www.craigrevelhorwood.com/',
 u'Daniel Brocklebank': u'http://www.dbonline.org/',
 u'Danny Adams': u'http://www.circushilarious.co.uk/',
 u'Dave Benson-Phillips': u'http://www.davebensonphillips.co.uk/',
 u'David McClelland': u'http://www.davidmcclelland.co.uk',
 u'David Robbins': u'http://www.davidrobbins.co.uk',
 u'David Van Day': u'http://www.davidvanday.co.uk/',
 u'Denise Pitter': u'http://www.denisepitter.com/',
 u'Dominic Cazenove': u'http://www.dominiccazenove.co.uk',
 u'Don Maclean': u'http://www.maclean7141.fsnet.co.uk/',
 u'Douglas Mounce': u'http://www.douglasmounce.com',
 u'Elaine C. Smith': u'http://www.elainecsmith.com/',
 u'Eric Potts': u'http://www.ericpotts.co.uk',
 u'Fifi': u'http://www.fifiandtheflowertots.com',
 u'Gabrielle Bradshaw': u'http://www.geocities.com/gabriellebradshaw/index.html',
 u'George Takei': u'http://www.georgetakei.com/',
 u'George Wood': u'http://www.george-wood.com',
 u'Graham Hoadly': u'http://www.hoadly.co.uk',
 u'Herbie Adams': u'http://www.herbieadams.com/',
 u"Hilary O'Neil": u'http://www.hilaryoneil.com',
 u"Ian 'H' Watkins": u'http://www.ian-h-watkins.com/',
 u'Ian Adams': u'http://www.ianadams.co.uk',
 u'Ian Ganderton': u'http://www.iganderton.com',
 u'Jamie Rickers': u'http://www.jamierickers.com/',
 u'Jane Asher': u'http://www.jane-asher.co.uk/',
 u'Jane Ledsom': u'http://www.janeledsom.com',
 u'Jean Rogers': u'http://www.jeanrogers.net/',
 u'Jeffrey Holland': u'http://www.jeffreyholland.co.uk',
 u'Jemma Carlisle': u'http://www.jemmacarlisle.com',
 u'Jenna Louise Coleman': u'http://www.jennalcoleman.com/',
 u'Jess Conrad': u'http://www.jessconrad.com',
 u'Jessica Negus': u'http://www.jessicanegus.co.uk/',
 u'Joe Pasquale': u'http://www.joepasquale.com',
 u'Joe Standerline': u'http://www.joestanderline.co.uk',
 u'John Barrowman': u'http://www.johnbarrowman.com/',
 u'John Hannibal': u'http://www.johnhannibal.co.uk/',
 u'Johnny Mac': u'http://www.johnnymac.info',
 u'Jon Lee': u'http://www.jonleeofficial.com/',
 u'Jonathan Shotton': u'http://www.enchantingmagic.com',
 u'Jonathan Wilkes': u'http://www.jonathanwilkes.com',
 u'Julian Clary': u'http://julianclary.co.uk/',
 u'Kate Rawson': u'http://katerawson.co.uk/',
 u'Keith Harris and Orville': u'http://www.keithharrisandorville.co.uk',
 u'Keith Jack': u'http://www.keithjack.com/',
 u'Kelle Bryan': u'http://www.kellebryan.co.uk/',
 u'Kev Orkian': u'http://www.kev-orkian.com/',
 u'Kevin James': u'http://www.kevinjames.info',
 u'Kevin Johns': u'http://www.kevinjohns.net/',
 u'Laura Hamilton': u'http://www.laurahamilton.co.uk',
 u'Letitia Dean': u'http://www.letitiadean.co.uk',
 u'Lewis Bradley': u'http://www.lewisbradleyofficial.com/',
 u'Liam Mellor': u'http://www.liammellor.co.uk',
 u'Mark Evans': u'http://www.markevansonline.co.uk/',
 u'Mark Siney': u'http://www.marksiney.com',
 u'Martin Ramsdin': u'http://www.martinramsdin.co.uk',
 u'Maurice Thorogood': u'http://www.mauricethorogood.co.uk',
 u'Max Somerset': u'http://www.maxsomerset.com/',
 u'Michelle Whitney': u'http://www.michellewhitney.co.uk',
 u'Mickey Rooney': u'http://www.mickeyrooney.com/',
 u'Mike Holoway': u'http://www.myspace.com/mikeholowaysolo',
 u'Mister Maker': u'http://www.mistermaker.com/',
 u'Natalie Cleverley': u'http://www.nataliecleverley.com/',
 u'Neil Hurst': u'http://www.neilhurst.co.uk',
 u'Nick Wilton': u'http://www.nickwilton.co.uk',
 u'Owen Money': u'http://www.owen-money.com/',
 u'Paul Morse': u'http://www.paulmorseactor.com',
 u'Paul Roberts': u'http://www.soulsec.com',
 u'Paul Tate': u'http://www.paultateproductions.co.uk',
 u'Paul Zerdin': u'http://www.paulzerdin.com/',
 u'Peter Duncan': u'http://www.heresoneimadeearlier.com',
 u'Ray Quinn': u'http://www.rayquinnmusic.com',
 u'Rosie Ashe': u'http://www.rosemary.ashe.ukonline.co.uk/',
 u'Sarah Jane Buckley': u'http://www.sarahjanebuckley.com/',
 u'Sarah-Jane Honeywell': u'http://www.sarah-jane.biz',
 u'Scott St Martyn': u'http://www.scottstmartyn.co.uk',
 u'Simmons and Simmons': u'http://www.simmonsandsimmons.org.uk',
 u'Simon Bashford': u'http://www.simonbashford.co.uk',
 u'Sooty and Sweep': u'http://www.its-behind-you.com/Sooty%20&%20Sweep',
 u'Stacey Cadman': u'http://www.staceycadman.co.uk',
 u'Stefan Dennis': u'http://www.stefandennis.com/',
 u'Steve Royle': u'http://www.steveroyle.co.uk/',
 u'Steve Walls': u'http://www.stevewalls.co.uk',
 u'Su Pollard': u'http://www.supollard.co.uk',
 u'The Chuckle Brothers': u'http://www.thechucklebrothersontour.co.uk/',
 u'The Citrus Brothers': u'http://www.citrusbrothers.com/',
 u'The Grumbleweeds': u'http://www.thegrumbleweeds.co.uk/',
 u'The Krankies': u'http://krankies.moonfruit.com/',
 u'Tim Vine': u'http://www.timvine.com/',
 u'Toyah Wilcox': u'http://www.toyahwillcox.com',
 u'Vicki Michelle': u'http://www.vickimichelle.co.uk/',
 u'Vicky Longley': u'http://www.genieinthehouse.com/vick/'
}

theatres = {
 u'Albans Arena,St. Albans': {'links': set([(u'http://www.alban-arena.co.uk', u'Albans Arena,St. Albans')]),
                              'logos': set([u'http://www.its-behind-you.com/images/stalbanslogo.jpg'])},
 u'Albert Halls, Bolton': {'links': set([(u'http://www.alberthalls-bolton.co.uk', u'Albert Halls, Bolton')]),
                           'logos': set([u'http://www.its-behind-you.com/images/TheAlbertHallsBolton.jpg'])},
 u'Alexandra Theatre, Bognor Regis': {'links': set([(u'http://www.alexandratheatre.co.uk', u'Alexandra Theatre, Bognor Regis')]),
                                      'logos': set([u'http://www.its-behind-you.com/images/AlexBogLogo.jpg'])},
 u'Ashcroft Theatre, Croydon': {'links': set([(u'http://www.fairfield.co.uk', u'Ashcroft Theatre, Croydon')])},
 u'Assembly Hall Theatre, Tunbridge Wells': {'links': set([(u'http://www.assemblyhalltheatre.co.uk', u'Assembly Hall Theatre, Tunbridge Wells')]),
                                             'logos': set([u'http://www.its-behind-you.com/images/Tunbridge-Wells.jpg'])},
 u'Assembly Rooms, Derby': {'links': set([(u'http://www.assemblyrooms-derby.co.uk/', u'Assembly Rooms, Derby')]),
                            'logos': set([u'http://www.its-behind-you.com/images/Assembly%20Rooms%20Logo%20Col.jpg'])},
 u'Beck Theatre, Hayes': {'links': set([(u'http://www.becktheatre.org.uk', u'Beck Theatre, Hayes')]),
                          'logos': set([u'http://www.its-behind-you.com/images/Beck-logo08.jpg'])},
 u'Belgrade Theatre, Coventry': {'links': set([(u'http://www.belgrade.co.uk', u'Belgrade Theatre, Coventry')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/BelgradeCoventry.jpg'])},
 u'Bell Performing Arts Centre, Surrey British Columbia, Canada': {},
 u'Blackfriars Arts Centre, Boston': {'links': set([(u'http://www.blackfriarsartscentre.co.uk', u'Blackfriars Arts Centre, Boston')])},
 u'Blackpool Opera House': {'links': set([(u'http://www.blackpoollive.com/', u'Blackpool Opera House')])},
 u'Blackwood Miners Institute': {'links': set([(u'http://www.b3live.co.uk/page.php?id=3', u'Blackwood Miners Institute')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/newbwoodlogo2.jpg'])},
 u'Bournemouth Pavilion': {'links': set([(u'http://www.bic.co.uk', u'Bournemouth Pavilion')]),
                           'logos': set([u'http://www.its-behind-you.com/images/logobournemouth.gif'])},
 u'Brewery Arts Centre, Kendal': {'links': set([(u'http://www.breweryarts.co.uk/', u'Brewery Arts Centre, Kendal')]),
                                  'logos': set([u'http://www.its-behind-you.com/images/BreweryArts.jpg'])},
 u'Bristol Hippodrome': {'links': set([(u'http://www.bristol-hippodrome.co.uk', u'Bristol Hippodrome')]),
                         'logos': set([u'http://www.its-behind-you.com/images/BristolHippodrome.jpg'])},
 u'Britannia Pier, Great Yarmouth': {'links': set([(u'http://www.britannia-pier.co.uk', u'Britannia Pier, Great Yarmouth')])},
 u'Broxbourne Civic Theatre': {'links': set([(u'http://www.broxbourne.gov.uk/Enjoying_Broxbourne/civichall.htm', u'Broxbourne Civic Theatre')]),
                               'logos': set([u'http://www.its-behind-you.com/images/NewBroxLgeWWW.jpg'])},
 u'Brunton Theatre, Musselburgh': {'links': set([(u'http://www.bruntontheatre.co.uk/', u'Brunton Theatre, Musselburgh')]),
                                   'logos': set([u'http://www.its-behind-you.com/images/Brunton%20Theatre%20Logo.jpg'])},
 u'Buxton Opera House': {'links': set([(u'http://www.buxton-opera.co.uk', u'Buxton Opera House')]),
                         'logos': set([u'http://www.its-behind-you.com/images/Logo_Buxton_Opera_House.jpg'])},
 u'Camberley Theatre': {'links': set([(u'http://www.camberleytheatre.biz', u'Camberley Theatre')]),
                        'logos': set([u'http://www.its-behind-you.com/images/camb-col-logo.jpg'])},
 u'Cambridge Arts Theatre': {'links': set([(u'http://www.cambridgeartstheatre.com', u'Cambridge Arts Theatre')]),
                             'logos': set([u'http://www.its-behind-you.com/images/catlogo.gif'])},
 u'Campus West Theatre, Welwyn Garden City': {},
 u'Central Theatre, Chatham': {'links': set([(u'http://www.medway.gov.uk/index/leisure/theatres/6016.html', u'Central Theatre, Chatham')]),
                               'logos': set([u'http://www.its-behind-you.com/images/Central-Theatre.jpg'])},
 u'Charter Theatre, Preston': {'links': set([(u'http://www.prestonguildhall.com/', u'Charter Theatre, Preston')]),
                               'logos': set([u'http://www.its-behind-you.com/images/Charterlogo09.jpg'])},
 u'Churchill Theatre, Bromley': {'links': set([(u'http://www.churchilltheatre.co.uk', u'Churchill Theatre, Bromley')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/bromleylogonew.jpg'])},
 u'Civic Centre, Aylesbury': {'links': set([(u'http://www.aylesburycivic.org', u'Civic Centre, Aylesbury')]),
                              'logos': set([u'http://www.its-behind-you.com/images/ayles30yrssm.gif'])},
 u'Civic Hall, Bedworth': {'links': set([(u'http://www.civichallinbedworth.co.uk', u'Civic Hall, Bedworth')])},
 u'Civic Theatre, Chelmsford': {'links': set([(u'http://www.chelmsford.gov.uk/theatres', u'Civic Theatre, Chelmsford')])},
 u'Civic Theatre, Darlington': {'links': set([(u'http://www.darlingtonarts.co.uk', u'Civic Theatre, Darlington')])},
 u'Civic Theatre, Rotherham': {'links': set([(u'http://www.rotherham.gov.uk/graphics/Leisure/Theatres/', u'Civic Theatre, Rotherham')]),
                               'logos': set([u'http://www.its-behind-you.com/images/RotherhamTheatres1.jpg'])},
 u'Cliffs Pavilion, Southend': {'links': set([(u'http://www.thecliffspavilion.co.uk', u'Cliffs Pavilion, Southend')]),
                                'logos': set([u'http://www.its-behind-you.com/images/logo_cliffs.jpg'])},
 u'Clyde Auditorium, Scottish Exhibition and Conference Centre, Glasgow': {'links': set([(u'http://www.secc.co.uk', u'Clyde Auditorium, Scottish Exhibition and Conference Centre, Glasgow')])},
 u'Cochrane Theatre, London': {'links': set([(u'http://www.cochranetheatre.co.uk', u'Cochrane Theatre, London')])},
 u'Coliseum Theatre, Oldham': {'links': set([(u'http://www.coliseum.org.uk', u'Coliseum Theatre, Oldham')]),
                               'logos': set([u'http://www.its-behind-you.com/images/OldhamColiseumLogo.jpg'])},
 u'Connaught Theatre, Worthing': {'links': set([(u'http://www.worthingtheatres.co.uk', u'Connaught Theatre, Worthing')])},
 u'Corn Exchange, Kings Lynn': {'links': set([(u'http://www.kingslynncornexchange.co.uk/', u'Corn Exchange, Kings Lynn')])},
 u'Corn Exchange, Newbury': {'links': set([(u'http://www.cornexchangenew.com/', u'Corn Exchange, Newbury')]),
                             'logos': set([u'http://www.its-behind-you.com/images/CornExchangeNewburygraphic.jpg'])},
 u'Custom House, South Shields': {'links': set([(u'http://www.customshouse.co.uk', u'Custom House, South Shields')])},
 u'Darwen Library Theatre': {'links': set([(u'http://www.darwenlibrarytheatre.com/', u'Darwen Library Theatre')])},
 u'De Montfort Hall, Leicester': {'links': set([(u'http://www.demontforthall.co.uk', u'De Montfort Hall, Leicester')])},
 u'Devonshire Park Theatre, Eastbourne': {'links': set([(u'http://www.eastbournetheatres.co.uk/', u'Devonshire Park Theatre, Eastbourne')])},
 u'Doncaster Civic Theatre': {'links': set([(u'http://www.doncastercivic.co.uk/', u'Doncaster Civic Theatre')]),
                              'logos': set([u'http://www.its-behind-you.com/images/logodoncaster.jpg'])},
 u'Doncaster Dome': {},
 u'Dorking Halls': {'links': set([(u'http://www.dorkinghalls.org', u'Dorking Halls')])},
 u'Eden Court Theatre, Inverness': {'links': set([(u'http://www.eden-court.co.uk', u'Eden Court Theatre, Inverness')])},
 u'Embassy Centre, Skegness': {'links': set([(u'http://www.embassytheatre.co.uk/', u'Embassy Centre, Skegness')]),
                               'logos': set([u'http://www.its-behind-you.com/images/EMBASSY-LOGO.jpg'])},
 u'Empire Theatre, Consett': {'links': set([(u'http://www.derwentside.gov.uk/index.cfm?articleid=10774', u'Empire Theatre, Consett')]),
                              'logos': set([u'http://www.its-behind-you.com/images/EmpireConsettLogo.jpg'])},
 u'Epsom Playhouse': {'links': set([(u'http://www.epsomplayhouse.co.uk', u'Epsom Playhouse')]),
                      'logos': set([u'http://www.its-behind-you.com/images/EpsomPlayhouse.jpg'])},
 u'Ferneham Hall, Fareham': {'links': set([(u'http://www.fareham.gov.uk/fernehamhall', u'Ferneham Hall, Fareham')]),
                             'logos': set([u'http://www.its-behind-you.com/images/fhall-logo.jpg'])},
 u'Festival Theatre, Malvern': {'links': set([(u'http://www.malvern-theatres.co.uk', u'Festival Theatre, Malvern')]),
                                'logos': set([u'http://www.its-behind-you.com/images/malvern_logo_sm.gif'])},
 u'Floral Pavilion, New Brighton': {'links': set([(u'http://www.floralpavilion.com', u'Floral Pavilion, New Brighton')]),
                                    'logos': set([u'http://www.its-behind-you.com/images/florallogo.jpg'])},
 u'Forum 28, Barrow-in-Furness': {'links': set([(u'http://www.forumtwentyeight.co.uk', u'Forum 28, Barrow-in-Furness')])},
 u'Gala Theatre, Durham': {'links': set([(u'http://www.galadurham.co.uk', u'Gala Theatre, Durham')]),
                           'logos': set([u'http://www.its-behind-you.com/images/galalogo_red.jpg'])},
 u'Garrick Theatre, Lichfield': {'links': set([(u'http://www.lichfieldgarrick.com', u'Garrick Theatre, Lichfield')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/LGARlogo.jpg'])},
 u'Georgian Theatre Royal, Richmond (Yorkshire)': {'links': set([(u'http://www.georgiantheatreroyal.co.uk/', u'Georgian Theatre Royal, Richmond (Yorkshire)')])},
 u'Glasgow Pavilion': {'links': set([(u'http://www.paviliontheatre.co.uk', u'Glasgow Pavilion')]),
                       'logos': set([u'http://www.its-behind-you.com/images/GlasgowPavillion.jpg'])},
 u'Gordon Craig Theatre, Stevenage': {'links': set([(u'http://www.gordon-craig.co.uk/', u'Gordon Craig Theatre, Stevenage')]),
                                      'logos': set([u'http://www.its-behind-you.com/images/StevenageTheatre-Logo.jpg'])},
 u'Gorleston Pavilion': {'links': set([(u'http://www.gorlestonpavilion.co.uk/', u'Gorleston Pavilion')])},
 u'Gracie Fields Theatre, Rochdale': {'links': set([(u'http://www.graciefieldstheatre.com/', u'Gracie Fields Theatre, Rochdale')])},
 u'Grand Opera House, Belfast': {'links': set([(u'http://www.goh.co.uk', u'Grand Opera House, Belfast')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/GrandOperaHouse.jpg'])},
 u'Grand Opera House, York': {'links': set([(u'http://www.york-operahouse.co.uk', u'Grand Opera House, York')]),
                              'logos': set([u'http://www.its-behind-you.com/images/GrandYorkLogo.jpg'])},
 u'Grand Pavilion, Porthcawl': {'links': set([(u'http://www.grandpavilion.co.uk/', u'Grand Pavilion, Porthcawl')]),
                                'logos': set([u'http://www.its-behind-you.com/images/logoporthcawl.jpg'])},
 u'Grand Theatre, Blackpool': {'links': set([(u'http://www.blackpoolgrand.co.uk/', u'Grand Theatre, Blackpool')]),
                               'logos': set([u'http://www.its-behind-you.com/images/logoblackpool_new.jpg'])},
 u'Grand Theatre, Swansea': {'links': set([(u'http://www.swanseagrand.co.uk', u'Grand Theatre, Swansea')]),
                             'logos': set([u'http://www.its-behind-you.com/images/GRAND-large-bw-logo.jpg'])},
 u'Grand Theatre, Wolverhampton': {'links': set([(u'http://www.grandtheatre.co.uk', u'Wolverhampton')]),
                                   'logos': set([u'http://www.its-behind-you.com/images/WolvGrandLogo09.jpg'])},
 u'Greenwich Theatre': {'links': set([(u'http://www.greenwichtheatre.org.uk', u'Greenwich Theatre')]),
                        'logos': set([u'http://www.its-behind-you.com/images/gt_logo.gif'])},
 u'Grimsby Auditorium': {'links': set([(u'http://www.grimsbyauditorium.org.uk', u'Grimsby Auditorium')]),
                         'logos': set([u'http://www.its-behind-you.com/images/logogrimsby.gif'])},
 u'Grove Theatre, Dunstable': {'links': set([(u'http://www.grovetheatre.co.uk/', u'Grove Theatre, Dunstable')]),
                               'logos': set([u'http://www.its-behind-you.com/images/grovedunstable.jpg'])},
 u'Hackney Empire Theatre': {'links': set([(u'http://www.hackneyempire.co.uk', u'Hackney Empire Theatre')]),
                             'logos': set([u'http://www.its-behind-you.com/images/Hackney_Logo2008.jpg'])},
 u'Harlequin Theatre, Redhill': {'links': set([(u'http://www.harlequin-theatre.co.uk', u'Harlequin Theatre, Redhill')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/theatre%20%20cinema%20logo.jpg'])},
 u'Harrogate Theatre': {'links': set([(u'http://www.harrogatetheatre.org', u'Harrogate Theatre')]),
                        'logos': set([u'http://www.its-behind-you.com/images/logoharrogate.jpg'])},
 u'Hazlitt Theatre, Maidstone': {'links': set([(u'http://www.hazlittartscentre.co.uk', u'Hazlitt Theatre, Maidstone')])},
 u'Hexagon Theatre, Reading': {'links': set([(u'http://www.readingarts.com', u'Hexagon Theatre, Reading')])},
 u'Hippodrome Theatre, Birmingham': {'links': set([(u'http://www.birminghamhippodrome.com', u'Hippodrome Theatre, Birmingham')]),
                                     'logos': set([u'http://www.its-behind-you.com/images/brumlogo.jpg'])},
 u"His Majesty's, Aberdeen": {'links': set([(u'http://www.hmtheatre.com', u"His Majesty's, Aberdeen")]),
                              'logos': set([u'http://www.its-behind-you.com/images/logoHMT.jpg'])},
 u'Hull New Theatre': {'links': set([(u'http://www.hullcc.gov.uk/hullnewtheatre', u'Hull New Theatre')]),
                       'logos': set([u'http://www.its-behind-you.com/images/newtheatrelogo.jpg'])},
 u'Ipswich Regent Theatre': {'links': set([(u'http://www.ipswichregent.com', u'Ipswich Regent Theatre')]),
                             'logos': set([u'http://www.its-behind-you.com/images/IpswichRegentLogosmall.jpg'])},
 u'White Rock Theatre, Hastings': {'links': set([(u'http://www.whiterocktheatre.org.uk/', u'White Rock Theatre, Hastings')]),
                                   'logos': set([u'http://www.its-behind-you.com/images/white-rock-theatre_logo.jpg'])},
 u'KD Studio Theatre, Dallas, Texas': {},
 u'Kenneth More Theatre, Ilford': {'links': set([(u'http://www.kenneth-more-theatre.co.uk', u'Kenneth More Theatre, Ilford')]),
                                   'logos': set([u'http://www.its-behind-you.com/images/KMTword_small.jpg'])},
 u"King George's Hall, Blackburn": {'links': set([(u'http://www.kinggeorgeshall.com', u"King George's Hall, Blackburn")])},
 u'Kings Theatre, Edinburgh': {'links': set([(u'http://www.eft.co.uk', u'Kings Theatre, Edinburgh')]),
                               'logos': set([u'http://www.its-behind-you.com/images/kingsedinburgh.jpg'])},
 u'Kings Theatre, Glasgow': {'links': set([(u'http://www.kings-glasgow.co.uk', u'Kings Theatre, Glasgow')]),
                             'logos': set([u'http://www.its-behind-you.com/images/glasgowlogo.jpg'])},
 u'Kings Theatre, Southsea': {'links': set([(u'http://www.kings-southsea.com', u'Kings Theatre, Southsea')])},
 u'Leas Cliff Hall, Folkestone': {'links': set([(u'http://www.leascliffhall.co.uk/', u'Leas Cliff Hall, Folkestone')])},
 u'Lincoln Drill Hall': {'links': set([(u'http://www.lincolndrillhall.com', u'Lincoln Drill Hall')]),
                         'logos': set([u'http://www.its-behind-you.com/images/DrillHallLogo.jpg'])},
 u'Lyceum Theatre, Crewe': {'links': set([(u'http://www.lyceumtheatre.net', u'Lyceum Theatre, Crewe')]),
                            'logos': set([u'http://www.its-behind-you.com/images/Lyceum-Theatre-Crewe.jpg'])},
 u'Lyceum Theatre, Sheffield': {'links': set([(u'http://www.sheffieldtheatres.co.uk', u'Lyceum Theatre, Sheffield')]),
                                'logos': set([u'http://www.its-behind-you.com/images/S-Lyceum-Mono.gif'])},
 u'Macrobert, Stirling': {'links': set([(u'http://www.macrobert.org', u'Macrobert, Stirling')])},
 u'Majestic Theatre, Retford': {'links': set([(u'http://www.majestictheatre.co.uk/', u'Majestic Theatre, Retford')])},
 u'Marina Theatre , Lowestoft': {'links': set([(u'http://www.marinatheatre.co.uk', u'Marina Theatre')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/Lowestoft-Marina-logo.gif'])},
 u'Marlowe Theatre Arena, Canterbury': {'links': set([(u'http://www.newmarlowetheatre.org.uk/', u'Marlowe Theatre Arena, Canterbury')]),
                                        'logos': set([u'http://www.its-behind-you.com/images/MarloweMono.jpg'])},
 u'Mayflower Theatre, Southampton': {'links': set([(u'http://www.the-mayflower.com', u'Mayflower Theatre, Southampton')]),
                                     'logos': set([u'http://www.its-behind-you.com/images/mayflower-logo_new.gif'])},
 u'Middlesbrough Theatre': {'links': set([(u'http://www.middlesbrough.gov.uk/entertainment', u'Middlesbrough Theatre')])},
 u'Middleton Arena': {'links': set([(u'http://www.middletonarena.com', u'Middleton Arena')])},
 u'Millfield Theatre, Edmonton (London)': {'links': set([(u'http://www.millfieldtheatre.co.uk', u'Millfield Theatre, Edmonton')]),
                                           'logos': set([u'http://www.its-behind-you.com/images/09millfieldlogo.jpg'])},
 u'Milton Keynes Theatre': {'links': set([(u'http://www.miltonkeynestheatre.com', u'Milton Keynes Theatre')]),
                            'logos': set([u'http://www.its-behind-you.com/images/milton_keyneslogo.jpg'])},
 u'Motherwell Theatre': {'links': set([(u'http://www.northlanarkshire.gov.uk', u'Motherwell Theatre')])},
 u'Muni Arts Centre, Pontypridd': {'links': set([(u'http://www.rct-arts.co.uk/', u'Muni Arts Centre, Pontypridd')])},
 u'Municipal Hall, Colne': {'links': set([(u'http://www.pendleleisuretrust.co.uk', u'Municipal Hall, Colne')])},
 u'Museum Theatre, Chennai (India)': {},
 u'New Theatre, Cardiff': {'links': set([(u'http://www.newtheatrecardiff.co.uk/', u'New Theatre, Cardiff')]),
                           'logos': set([u'http://www.its-behind-you.com/images/newtheatrecardiff.jpg'])},
 u'New Victoria Theatre, Woking': {'links': set([(u'http://www.theambassadors.com/woking/', u'New Victoria Theatre, Woking')]),
                                   'logos': set([u'http://www.its-behind-you.com/images/wokinglogo.jpg'])},
 u'New Wimbledon Theatre': {'links': set([(u'http://www.theambassadors.com/newwimbledon/', u'New Wimbledon Theatre')]),
                            'logos': set([u'http://www.its-behind-you.com/images/wimbledonlogo.jpg'])},
 u'Octagon Theatre, Yeovil': {'links': set([(u'http://www.octagon-theatre.co.uk', u'Octagon Theatre, Yeovil')]),
                              'logos': set([u'http://www.its-behind-you.com/images/logooctagonyeovil.jpg'])},
 u'Opera House, Manchester': {'links': set([(u'http://www.manchestertheatres.co.uk', u'Opera House, Manchester')]),
                              'logos': set([u'http://www.its-behind-you.com/images/ffelogomanchester.jpg'])},
 u'Oswaldtwistle Civic Theatre': {},
 u'Oxford Playhouse': {'links': set([(u'http://www.oxfordplayhouse.co.uk', u'Oxford Playhouse')])},
 u'Palace Theatre, Kilmarnock': {'links': set([(u'http://www.palacetheatre.biz', u'Palace Theatre, Kilmarnock')])},
 u'Palace Theatre, Manchester': {'links': set([(u'http://www.manchestertheatres.co.uk', u'Palace Theatre, Manchester')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/PalaceManchLogo.jpg'])},
 u'Palace Theatre, Mansfield': {'links': set([(u'http://www.mansfield-dc.gov.uk/palacetheatre/', u'Palace Theatre, Mansfield')]),
                                'logos': set([u'http://www.its-behind-you.com/images/logomansfield.gif'])},
 u'Palace Theatre, Newark': {'links': set([(u'http://www.palacenewark.com', u'Palace Theatre, Newark')]),
                             'logos': set([u'http://www.its-behind-you.com/images/NewarkPalacelogo.jpg'])},
 u'Parc and Dare Theatre, Treorchy': {'links': set([(u'http://www.rct-arts.co.uk/', u'Parc and Dare Theatre, Treorchy')])},
 u'Pavilion Theatre, Rhyl': {'links': set([(u'http://www.rhylpavilion.co.uk', u'Pavilion Theatre, Rhyl')]),
                             'logos': set([u'http://www.its-behind-you.com/images/logorhyl.gif'])},
 u'Pavilion Theatre, Weymouth': {'links': set([(u'http://www.weymouth.gov.uk/Leisure/Pavilion/home.asp?svid=815', u'Pavilion Theatre, Weymouth')])},
 u'Peepul Centre, Leicester': {'links': set([(u'http://www.peepulcentre.com', u'Peepul Centre, Leicester')]),
                               'logos': set([u'http://www.its-behind-you.com/images/peepulcentrelogo.jpg'])},
 u'Playhouse Theatre, Nottingham': {'links': set([(u'http://www.nottinghamplayhouse.co.uk', u'Playhouse Theatre, Nottingham')]),
                                    'logos': set([u'http://www.its-behind-you.com/images/NottinghamPlayhouse.jpg'])},
 u'Playhouse, Weston-Super-Mare': {'links': set([(u'http://www.theplayhouse.co.uk', u'Playhouse, Weston-Super-Mare')]),
                                   'logos': set([u'http://www.its-behind-you.com/images/PHLogo.jpg'])},
 u'Plowright Theatre, Scunthorpe': {'links': set([(u'http://www.northlincs.gov.uk/NorthLincs/Leisure/theatres/', u'Plowright Theatre, Scunthorpe')])},
 u'Pomegranate, Chesterfield': {'links': set([(u'http://www.pomegranatetheatre.co.uk/', u'Pomegranate, Chesterfield')]),
                                'logos': set([u'http://www.its-behind-you.com/images/logopom.jpg'])},
 u'Prince of Wales, Cannock': {'links': set([(u'http://www.cannockchasedc.gov.uk/princeofwales', u'Prince of Wales, Cannock')])},
 u'Princes Hall, Aldershot': {'links': set([(u'http://www.princeshall.com', u'Princes Hall, Aldershot')]),
                              'logos': set([u'http://www.its-behind-you.com/images/aldershotlogo.jpg'])},
 u'Princess Theatre, Clacton on Sea': {},
 u'Princess Theatre, Hunstanton': {'links': set([(u'http://www.princesstheatrehunstanton.co.uk/', u'Princess Theatre, Hunstanton')])},
 u'Princess Theatre, Torquay': {'links': set([(u'http://www.princesstheatre.org.uk', u'Princess Theatre, Torquay')]),
                                'logos': set([u'http://www.its-behind-you.com/images/torquaycmyk.jpg'])},
 u"Queen's Theatre, Barnstaple": {'links': set([(u'http://www.northdevontheatres.org.uk', u"Queen's Theatre, Barnstaple")]),
                                  'logos': set([u'http://www.its-behind-you.com/images/queenstheatrebarnstaple.jpg'])},
 u'Queens Theatre, Burslem': {'links': set([(u'http://www.queenstheatreburslem.com/', u'Queens Theatre, Burslem')])},
 u'Radlett Centre, Radlett': {'links': set([(u'http://www.radlettcentre.co.uk', u'Radlett Centre, Radlett')])},
 u'Regent Theatre, Stoke on Trent': {'links': set([(u'http://www.regenttheatre.co.uk', u'Regent Theatre, Stoke on Trent')]),
                                     'logos': set([u'http://www.its-behind-you.com/images/stoke-on-trentlogo.jpg'])},
 u'Richmond Theatre': {'links': set([(u'http://www.theambassadors.com/richmond/', u'Richmond Theatre')]),
                       'logos': set([u'http://www.its-behind-you.com/images/richmondlogo.jpg'])},
 u'Riverfront Theatre, Newport': {'links': set([(u'http://www.newport.gov.uk/riverfront', u'Riverfront Theatre, Newport')]),
                                  'logos': set([u'http://www.its-behind-you.com/images/newport_logo_sm.jpg'])},
 u'Roses Theatre, Tewkesbury': {'links': set([(u'http://www.rosestheatre.org/', u'Roses Theatre, Tewkesbury')]),
                                'logos': set([u'http://www.its-behind-you.com/images/roses_logo.jpg'])},
 u'Royal Concert Hall, Nottingham': {'links': set([(u'http://www.royalcentre-nottingham.co.uk', u'Royal Concert Hall, Nottingham')]),
                                     'logos': set([u'http://www.its-behind-you.com/images/rchThumb.jpg'])},
 u'Royal Spa Centre, Leamington Spa': {'links': set([(u'http://www.warwickdc.gov.uk/RoyalSpaCentre/default.htm', u'Royal Spa Centre, Leamington Spa')])},
 u'Royal and Derngate, Northampton': {'links': set([(u'http://www.royalandderngate.co.uk', u'Royal and Derngate, Northampton')]),
                                      'logos': set([u'http://www.its-behind-you.com/images/productionimage2.jpg'])},
 u'Salisbury Playhouse': {'links': set([(u'http://www.salisburyplayhouse.com', u'Salisbury Playhouse')])},
 u'Sands Centre, Carlisle': {'links': set([(u'http://www.thesandscentre.co.uk', u'Sands Centre, Carlisle')]),
                             'logos': set([u'http://www.its-behind-you.com/images/SANDS_new.jpg'])},
 u'Shaw Theatre, London': {'links': set([(u'http://www.theshawtheatre.com/', u'Shaw Theatre, London')]),
                           'logos': set([u'http://www.its-behind-you.com/images/TheShawTheatreLondon.jpg'])},
 u'Sheringham Little Theatre': {'links': set([(u'http://www.sheringhamlittletheatre.com', u'Sheringham Little Theatre')]),
                                'logos': set([u'http://www.its-behind-you.com/images/SheringhamLittleTheatre_lit.jpg'])},
 u'Solihull Arts Centre': {'links': set([(u'http://www.solihull.gov.uk/arts', u'Solihull Arts Centre')]),
                           'logos': set([u'http://www.its-behind-you.com/images/solihull_arts.gif'])},
 u'South Holland Centre, Spalding': {'links': set([(u'http://www.southhollandcentre.co.uk', u'South Holland Centre, Spalding')])},
 u'Southport Theatre': {'links': set([(u'http://www.ofsstudio.org.uk', u'Southport Theatre')]),
                        'logos': set([u'http://www.its-behind-you.com/images/SouthportLogo.jpg'])},
 u'Spa Theatre, Bridlington': {'links': set([(u'http://www.bridlington.net/spa', u'Spa Theatre, Bridlington')]),
                               'logos': set([u'http://www.its-behind-you.com/images/SPA-logo.jpg'])},
 u"St David's Hall, Cardiff": {'links': set([(u'http://www.stdavidshallcardiff.co.uk', u"St David's Hall, Cardiff")])},
 u'Stockport Plaza': {'links': set([(u'http://www.stockportplaza.co.uk', u'Stockport Plaza')]),
                      'logos': set([u'http://www.its-behind-you.com/images/NewPlazaLogo.jpg'])},
 u'Sunderland Empire': {'links': set([(u'http://www.cclive.co.uk/sunderemp', u'Sunderland Empire')]),
                        'logos': set([u'http://www.its-behind-you.com/images/sunderland.jpg'])},
 u'Swallow Leisure Centre, Sittingbourne': {'links': set([(u'http://www.swallowsleisure.com/', u'Swallow Leisure Centre, Sittingbourne')]),
                                            'logos': set([u'http://www.its-behind-you.com/images/swallowsartscentre.jpg'])},
 u'Thameside Theatre, Grays': {'links': set([(u'http://www.thurrock.gov.uk/theatre', u'Thameside Theatre, Grays')])},
 u'The Alexandra Theatre, Birmingham': {'links': set([(u'http://www.birmingham-alexandra.co.uk', u'The Alexandra Theatre, Birmingham')]),
                                        'logos': set([u'http://www.its-behind-you.com/images/AlexBirmLogo.jpg'])},
 u'The Alhambra, Bradford': {'links': set([(u'http://www.bradford-theatres.co.uk', u'The Alhambra, Bradford')])},
 u'The Anvil, Basingstoke': {'links': set([(u'http://www.theanvil.org.uk', u'The Anvil, Basingstoke')]),
                             'logos': set([u'http://www.its-behind-you.com/images/basingstoke_logo.gif'])},
 u'The Brindley Arts Centre, Runcorn': {'links': set([(u'http://www2.halton.gov.uk/thebrindley/', u'The Brindley Arts Centre, Runcorn')])},
 u'The Broadway Theatre, Catford': {'links': set([(u'http://www.broadwaytheatre.org.uk/', u'The Broadway Theatre, Catford')]),
                                    'logos': set([u'http://www.its-behind-you.com/images/Broad(BW).jpg'])},
 u'The Byre Theatre, St Andrews': {'links': set([(u'http://www.byretheatre.com', u'The Byre Theatre, St Andrews')])},
 u'The Capitol, Horsham': {'links': set([(u'http://www.thecapitolhorsham.com', u'The Capitol, Horsham')]),
                           'logos': set([u'http://www.its-behind-you.com/images/capitologonew.jpg'])},
 u'The Carriageworks, Leeds': {'links': set([(u'http://www.carriageworkstheatre.org.uk/', u'The Carriageworks, Leeds')]),
                               'logos': set([u'http://www.its-behind-you.com/images/cw_logo_small.gif'])},
 u'The Civic Centre, Whitchurch': {},
 u'The Civic Hall, Winsford': {'links': set([(u'http://www.valeroyal.gov.uk', u'The Civic Hall, Winsford')])},
 u'The Coliseum, Aberdare': {'links': set([(u'http://www.rct-arts.co.uk/', u'The Coliseum, Aberdare')])},
 u'The Cressett, Peterborough': {'links': set([(u'http://www.cresset.co.uk', u'The Cressett, Peterborough')])},
 u'The Deco, Northampton': {'links': set([(u'http://www.thedeco.co.uk', u'The Deco, Northampton')]),
                            'logos': set([u'http://www.its-behind-you.com/images/thedecologo.jpg'])},
 u'The Elgiva, Chesham': {'links': set([(u'http://www.elgiva.com', u'The Elgiva, Chesham')])},
 u'The Empire Theatre, Liverpool': {'links': set([(u'http://www.liverpoolempire.org.uk', u'The Empire Theatre, Liverpool')]),
                                    'logos': set([u'http://www.its-behind-you.com/images/LiverpoolEmpire.jpg'])},
 u'The Everyman, Liverpool': {'links': set([(u'http://www.everymanplayhouse.com', u'The Everyman, Liverpool')])},
 u'The Festival Drayton Centre, Market Drayton': {'links': set([(u'http://www.festivaldraytoncentre.com/', u'The Festival Drayton Centre, Market Drayton')])},
 u'The Futurist Theatre, Scarborough': {'links': set([(u'http://www.futuristtheatre.co.uk', u'The Futurist Theatre, Scarborough')])},
 u'The Grange Theatre, Hartford': {'links': set([(u'http://www.thegrangetheatre.com/', u'The Grange Theatre, Hartford')]),
                                   'logos': set([u'http://www.its-behind-you.com/images/grangehartfordlogo.jpg'])},
 u'The Hall for Cornwall, Truro': {'links': set([(u'http://www.hallforcornwall.co.uk', u'The Hall for Cornwall, Truro')]),
                                   'logos': set([u'http://www.its-behind-you.com/images/H4C-logo-with-slogan.jpg'])},
 u'The Hawth, Crawley': {'links': set([(u'http://www.hawth.co.uk', u'The Hawth, Crawley')]),
                         'logos': set([u'http://www.its-behind-you.com/images/hawthcrawleylogo.jpg'])},
 u'The Journal Tyne Theatre, Newcastle': {'links': set([(u'http://www.thejournaltynetheatre.co.uk', u'The Journal Tyne Theatre, Newcastle')]),
                                          'logos': set([u'http://www.its-behind-you.com/images/logotynetheatre.jpg'])},
 u'The Key Theatre, Peterborough': {'links': set([(u'http://www.peterboroughkeytheatre.co.uk/', u'The Key Theatre, Peterborough')]),
                                    'logos': set([u'http://www.its-behind-you.com/images/KeyLogo.jpg'])},
 u'The Library Theatre, Luton': {'links': set([(u'http://www.lutonlibrarytheatre.co.uk', u'The Library Theatre, Luton')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/lutonlibrarylogo.jpg'])},
 u'The Lighthouse, Poole': {'links': set([(u'http://www.lighthousepoole.co.uk', u'The Lighthouse, Poole')])},
 u'The Orchard, Dartford': {'links': set([(u'http://www.orchardtheatre.co.uk', u'The Orchard, Dartford')]),
                            'logos': set([u'http://www.its-behind-you.com/images/orchardlogo.jpg'])},
 u'The Palace Theatre, Redditch': {'links': set([(u'http://www.redditchpalacetheatre.co.uk', u'The Palace Theatre, Redditch')]),
                                   'logos': set([u'http://www.its-behind-you.com/images/RedditchLogo.jpg'])},
 u'The Parkway Theatre & Cinema, Cleethorpes': {'links': set([(u'http://www.its-behind-you.com/https://www.parkwaycinemas.co.uk/', u'The Parkway Theatre & Cinema, Cleethorpes')]),
                                                'logos': set([u'http://www.its-behind-you.com/images/Parkway-Logo.jpg'])},
 u'The Pavilion, Worthing': {'links': set([(u'http://www.worthingtheatres.co.uk', u'The Pavilion, Worthing')])},
 u'The Place Theatre , Telford': {'links': set([(u'http://www.oakengates.ws', u', Telford')]),
                                  'logos': set([u'http://www.its-behind-you.com/images/theplacelogo.jpg'])},
 u'The Playhouse, Harlow': {'links': set([(u'http://www.playhouseharlow.com/', u'The Playhouse, Harlow')]),
                            'logos': set([u'http://www.its-behind-you.com/images/Largeplayhousebluelogo.jpg'])},
 u'The Stag, Sevenoaks': {'links': set([(u'http://www.stagsevenoaks.co.uk', u'The Stag, Sevenoaks')])},
 u'The Theatre Royal, Bury St Edmunds': {'links': set([(u'http://www.theatreroyal.org', u'The Theatre Royal, Bury St Edmunds')]),
                                         'logos': set([u'http://www.its-behind-you.com/images/trburystedlogo.jpg'])},
 u'The Wave Centre, Maryport': {'links': set([(u'http://www.thewavemaryport.co.uk/', u'The Wave Centre, Maryport')])},
 u'The Wyllyotts Theatre, Potters Bar': {'links': set([(u'http://www.wyllyottscentre.co.uk', u'The Wyllyotts Theatre, Potters Bar')])},
 u'Theatr Colwyn, Colwyn Bay': {'links': set([(u'http://www.theatrcolwyn.co.uk', u'Theatr Colwyn, Colwyn Bay')]),
                                'logos': set([u'http://www.its-behind-you.com/images/NewLogoCol.jpg'])},
 u'Theatre Brycheiniog, Brecon': {'links': set([(u'http://www.thaetrebrycheiniog.co.uk', u'Theatre Brycheiniog, Brecon')]),
                                  'logos': set([u'http://www.its-behind-you.com/images/theatrbrecon.gif'])},
 u'Theatre Royal and Opera House, Wakefield': {'links': set([(u'http://www.wakefieldtheatre.co.uk', u'Theatre Royal and Opera House, Wakefield')])},
 u'Theatre Royal, Bath': {'links': set([(u'http://www.theatreroyal.org.uk', u'Theatre Royal, Bath')]),
                          'logos': set([u'http://www.its-behind-you.com/images/trb_logo.jpg'])},
 u'Theatre Royal, Brighton': {'links': set([(u'http://www.theambassadors.com/theatreroyal/', u'Theatre Royal, Brighton')]),
                              'logos': set([u'http://www.its-behind-you.com/images/brightonlogo.jpg'])},
 u'Theatre Royal, Lincoln': {'links': set([(u'http://www.theatreroyallincoln.com', u'Theatre Royal, Lincoln')])},
 u'Theatre Royal, Newcastle upon Tyne': {'links': set([(u'http://www.theatreroyal.co.uk', u'Newcastle upon Tyne')]),
                                         'logos': set([u'http://www.its-behind-you.com/images/visicoroyal.gif'])},
 u'Theatre Royal, Norwich': {'links': set([(u'http://www.theatreroyalnorwich.co.uk', u'Theatre Royal, Norwich')]),
                             'logos': set([u'http://www.its-behind-you.com/images/norwich_tr.gif'])},
 u'Theatre Royal, Nottingham': {'links': set([(u'http://www.royalcentre-nottingham.co.uk', u'Theatre Royal, Nottingham')]),
                                'logos': set([u'http://www.its-behind-you.com/images/tr_nottlogo.jpg'])},
 u'Theatre Royal, Plymouth': {'links': set([(u'http://www.theatreroyal.com', u'Theatre Royal, Plymouth')]),
                              'logos': set([u'http://www.its-behind-you.com/images/home_logo.jpg'])},
 u'Theatre Royal, St. Helens': {'links': set([(u'http://www.sthelenstheatreroyal.co.uk/', u'Theatre Royal, St. Helens')]),
                                'logos': set([u'http://www.its-behind-you.com/images/StHelensTheatreRoyal.jpg'])},
 u'Theatre Royal, Winchester': {'links': set([(u'http://www.theatre-royal-winchester.co.uk', u'Theatre Royal, Winchester')]),
                                'logos': set([u'http://www.its-behind-you.com/images/TRWlogo.jpg'])},
 u'Theatre Royal, Windsor': {'links': set([(u'http://www.theatreroyalwindsor.co.uk', u'Theatre Royal, Windsor')]),
                             'logos': set([u'http://www.its-behind-you.com/images/TheatreRoyalWindsor.jpg'])},
 u'Theatre Royal, York': {'links': set([(u'http://www.yorktheatreroyal.co.uk/', u'Theatre Royal, York')]),
                          'logos': set([u'http://www.its-behind-you.com/images/YorkTheatreRoyal.jpg'])},
 u'Theatre Severn, Shrewsbury': {'links': set([(u'http://www.theatresevern.co.uk/', u'Theatre Severn, Shrewsbury')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/tslogo2009.jpg'])},
 u'Thwaites Empire Theatre, Blackburn': {'links': set([(u'http://www.thwaitestheatre.co.uk/', u'Thwaites Empire Theatre, Blackburn')])},
 u'Town Hall, Loughborough': {'links': set([(u'http://www.loughboroughtownhall.co.uk/', u'Town Hall, Loughborough')])},
 u'Towngate Theatre, Basildon': {'links': set([(u'http://www.basildon.gov.uk', u'Towngate Theatre, Basildon')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/basildonlogo.gif'])},
 u'Trinity Arts Centre, Gainsborough': {'links': set([(u'http://www.artsfortrinity.co.uk', u'Trinity Arts Centre, Gainsborough')])},
 u'Tron Theatre, Glasgow': {'links': set([(u'http://www.tron.co.uk/', u'Tron Theatre, Glasgow')])},
 u'Venue Cymru, Llandudno': {'links': set([(u'http://www.venuecymru.co.uk', u'Venue Cymru, Llandudno')]),
                             'logos': set([u'http://www.its-behind-you.com/images/nopic-lrg.jpg'])},
 u'Victoria Theatre, Halifax': {'links': set([(u'http://www.calderdale.gov.uk/tourism/victoriatheatre/', u'Victoria Theatre, Halifax')])},
 u'Warwick Arts Centre': {'links': set([(u'http://www.warwickartscentre.co.uk', u'Warwick Arts Centre')]),
                          'logos': set([u'http://www.its-behind-you.com/images/wacLogo.gif'])},
 u'Watersmeet Theatre, Rickmansworth': {'links': set([(u'http://www.threerivers.gov.uk/', u'Watersmeet Theatre, Rickmansworth')]),
                                        'logos': set([u'http://www.its-behind-you.com/images/watersmeet_new.gif'])},
 u'Watford Colloseum': {'links': set([(u'http://www.watford-colosseum.co.uk', u'Watford Colloseum')])},
 u'Webster Theatre, Arbroath': {'links': set([(u'http://www.webstertheatre.co.uk/', u'Webster Theatre, Arbroath')])},
 u'Welfare Theatre, Ystradgynlais': {'links': set([(u'http://www.thewelfare.co.uk/', u'Welfare Theatre, Ystradgynlais')])},
 u'Whitley Bay Playhouse': {'links': set([(u'http://www.playhousewhitleybay.co.uk', u'Whitley Bay Playhouse')])},
 u'Woodville Hall Theatre, Gravesend': {'links': set([(u'http://www.woodvillehalls.com', u'Woodville Hall Theatre, Gravesend')]),
                                        'logos': set([u'http://www.its-behind-you.com/images/Gravesend_logo.jpg'])},
 u'Wycombe Swan, High Wycombe': {'links': set([(u'http://www.wycombeswan.co.uk', u'Swan, High Wycombe')]),
                                 'logos': set([u'http://www.its-behind-you.com/images/wycombe_swan_logo1.jpg'])},
 u'Wyvern Theatre, Swindon': {'links': set([(u'http://www.wyverntheatre.org.uk/', u'Wyvern Theatre, Swindon')]),
                              'logos': set([u'http://www.its-behind-you.com/images/wyvern_logo2.gif'])},
 u'Yvonne Arnaud, Guildford': {'links': set([(u'http://www.yvonne-arnaud.co.uk', u'Yvonne Arnaud, Guildford')]),
                               'logos': set([u'http://www.its-behind-you.com/images/GuildfordTheatre-logo.jpg'])}
}
