# Generated by Django 2.2.17 on 2021-04-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Creator of image'),
        ),
        migrations.AddField(
            model_name='photo',
            name='license',
            field=models.CharField(blank=True, choices=[('own-work', 'Own work'), ('permitted', 'Granted permission to upload to Theatricalia'), ('Freely licensed', (('cc-by', 'Creative Commons Attribution'), ('cc-by-sa', 'Creative Commons Attribution-ShareAlike'), ('cc-by-nc-sa', 'Creative Commons Attribution-NonCommercial-ShareAlike'), ('cc-by-nc', 'Creative Commons Attribution-NonCommercial'), ('cc-by-nd', 'Creative Commons Attribution-NoDerivatives'), ('cc-by-nd-nc', 'Creative Commons Attribution-NonCommercial-NoDerivatives'), ('free-other', 'Other similar licence (provide source link)'))), ('Public domain', (('cc-zero', 'Public domain under CC-Zero licence'), ('pd-age', 'Public domain due to age'), ('pd-other', 'Other public domain')))], max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='source',
            field=models.URLField(blank=True, verbose_name='Source link'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(help_text='(required)', max_length=255),
        ),
    ]
