# Generated by Django 2.2.28 on 2023-02-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merged', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
