# Generated by Django 2.2.28 on 2023-02-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merged', '0002_redirect_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
