# Generated by Django 3.2.23 on 2023-11-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_auto_20161227_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cast',
            field=models.BooleanField(blank=True, help_text='Crew includes all non-cast, from director to musicians to producers', null=True, verbose_name='Cast/Crew'),
        ),
    ]
